-- This is an automatically generated class by FairyGUI. Please do not modify it.

local MainButton_Ticket = import(".MainButton_Ticket")
local MainButton_Gold = import(".MainButton_Gold")
local MainTopBar = import(".MainTopBar")
local MainButton_Gift = import(".MainButton_Gift")
local MainButton_Task = import(".MainButton_Task")
local MainButton_Day = import(".MainButton_Day")
local MainButton_Box = import(".MainButton_Box")
local MainButton_Mail = import(".MainButton_Mail")
local MainButton_Rotary = import(".MainButton_Rotary")
local MainBottomBar = import(".MainBottomBar")
local Hall = import(".Hall")
local Activity1Button_Close = import(".Activity1Button_Close")
local Activity1 = import(".Activity1")
local Activity2Button_Close = import(".Activity2Button_Close")
local Activity2 = import(".Activity2")
local Activity1Group = import(".Activity1Group")
local Activity2Group = import(".Activity2Group")
local MainButton_Lanterns = import(".MainButton_Lanterns")
local MainButton_Wild = import(".MainButton_Wild")
local MainButton_Hot = import(".MainButton_Hot")
local MainButton_Activity = import(".MainButton_Activity")
local MainButton_Ruby = import(".MainButton_Ruby")
local MainButton_Show = import(".MainButton_Show")
local MainCentre = import(".MainCentre")
local MainButton_Buy = import(".MainButton_Buy")
local MainButton_Jast = import(".MainButton_Jast")
local MainButton_Vip = import(".MainButton_Vip")
local MainButton_Pig = import(".MainButton_Pig")
local MainButton_Seting = import(".MainButton_Seting")

local HallBinder = class("HallBinder")

function HallBinder:BindAll()
    fgui.register_extension(MainButton_Ticket.URL, MainButton_Ticket)
    fgui.register_extension(MainButton_Gold.URL, MainButton_Gold)
    fgui.register_extension(MainTopBar.URL, MainTopBar)
    fgui.register_extension(MainButton_Gift.URL, MainButton_Gift)
    fgui.register_extension(MainButton_Task.URL, MainButton_Task)
    fgui.register_extension(MainButton_Day.URL, MainButton_Day)
    fgui.register_extension(MainButton_Box.URL, MainButton_Box)
    fgui.register_extension(MainButton_Mail.URL, MainButton_Mail)
    fgui.register_extension(MainButton_Rotary.URL, MainButton_Rotary)
    fgui.register_extension(MainBottomBar.URL, MainBottomBar)
    fgui.register_extension(Hall.URL, Hall)
    fgui.register_extension(Activity1Button_Close.URL, Activity1Button_Close)
    fgui.register_extension(Activity1.URL, Activity1)
    fgui.register_extension(Activity2Button_Close.URL, Activity2Button_Close)
    fgui.register_extension(Activity2.URL, Activity2)
    fgui.register_extension(Activity1Group.URL, Activity1Group)
    fgui.register_extension(Activity2Group.URL, Activity2Group)
    fgui.register_extension(MainButton_Lanterns.URL, MainButton_Lanterns)
    fgui.register_extension(MainButton_Wild.URL, MainButton_Wild)
    fgui.register_extension(MainButton_Hot.URL, MainButton_Hot)
    fgui.register_extension(MainButton_Activity.URL, MainButton_Activity)
    fgui.register_extension(MainButton_Ruby.URL, MainButton_Ruby)
    fgui.register_extension(MainButton_Show.URL, MainButton_Show)
    fgui.register_extension(MainCentre.URL, MainCentre)
    fgui.register_extension(MainButton_Buy.URL, MainButton_Buy)
    fgui.register_extension(MainButton_Jast.URL, MainButton_Jast)
    fgui.register_extension(MainButton_Vip.URL, MainButton_Vip)
    fgui.register_extension(MainButton_Pig.URL, MainButton_Pig)
    fgui.register_extension(MainButton_Seting.URL, MainButton_Seting)
end

return HallBinder